name: .NET Core Desktop

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: windows-latest
        if: contains(github.event.head_commit.message, '[upcode]') == true)
         
       